/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
using namespace cv;
using namespace std;
/* Header for class com_example_abb2_DetectIris */

#ifndef _Included_com_serenegiant_opencvwithuvc_DetectIris
#define _Included_com_serenegiant_opencvwithuvc_DetectIris
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_abb2_DetectIris
 * Method:    DetectCenter
 * Signature: (J)V
 */
void centerx(Mat& frame, Mat &frameg);

JNIEXPORT void JNICALL Java_com_serenegiant_opencvwithuvc_DetectIris_DetectCenter
  (JNIEnv *, jclass, jlong , jlong);

#ifdef __cplusplus
}
#endif
#endif
