/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"

//Including Android log for debugging purposes.
#include <android/log.h>
#define  LOG_TAG    "your-log-tag"
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
//Including Android log for debugging purposes.

/* Header for class com_example_anannyauberoi_testingcamtwo_OpenClass */
using namespace cv;

#ifndef _Included_com_example_anannyauberoi_testingcamtwo_OpenClass
#define _Included_com_example_anannyauberoi_testingcamtwo_OpenClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_anannyauberoi_testingcamtwo_OpenClass
 * Method:    detectIris
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_anannyauberoi_testingcamtwo_OpenClass_detectIris
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif