/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_example_anannyauberoi_testingcamtwo_cvClass */

using namespace cv;
#ifndef _Included_com_example_anannyauberoi_testingcamtwo_cvClass
#define _Included_com_example_anannyauberoi_testingcamtwo_cvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_anannyauberoi_testingcamtwo_cvClass
 * Method:    detect
 * Signature: (J)V
 */

//void detectfun(Mat& frame);
double modifiedLaplacian(Mat& src);

JNIEXPORT jstring JNICALL Java_com_example_anannyauberoi_testingcamtwo_cvClass_detect
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
