/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_abb2_cvClass */
#include "opencv2/opencv.hpp"
#include "opencv2/core/core.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
using namespace cv;
#ifndef _Included_com_example_anannyauberoi_appfinal_cvClass
#define _Included_com_example_anannyauberoi_appfinal_cvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_abb2_cvClass
 * Method:    detect
 * Signature: (J)Ljava/lang/String;
 */
 double modifiedLaplacian(Mat& src);
//modified laplacian is just the name.The code has been replaced by a better optimised version
JNIEXPORT jstring JNICALL Java_com_example_anannyauberoi_appfinal_cvClass_detect
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
